Fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,6 +7,16 @@ jobs:
   deploy-frontend:
     runs-on: ubuntu-latest
     steps:
+      - name: Wait for build
+        uses: fountainhead/action-wait-for-check@v1.0.0
+        id: wait-for-build
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          checkName: build
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      - name: Build failed
+        if: steps.wait-for-build.outputs.conclusion == 'failure'
+        run: echo "Build failed" && exit 1
       - uses: actions/download-artifact@v2
         with:
           name: static-assets
@@ -20,6 +30,16 @@ jobs:
   deploy-server:
     runs-on: ubuntu-latest
     steps:
+      - name: Wait for build
+        uses: fountainhead/action-wait-for-check@v1.0.0
+        id: wait-for-build
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          checkName: build
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      - name: Build failed
+        if: steps.wait-for-build.outputs.conclusion == 'failure'
+        run: echo "Build failed" && exit 1
       - uses: actions/checkout@v2
       - uses: hmanzur/actions-aws-eb@v1.0.0
         with:
